fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(&[
                "search_remote",
                "search_sites",
                "count_remote",
                "download_posts",
                "download_query",
                "list_jobs",
                "job_action",
                "job_notes",
                "clear_finished_jobs",
                "library_list",
                "library_folders",
                "library_import",
                "library_groups",
                "library_delete",
                "accounts_info",
                "account_save",
                "account_remove",
                "pixiv_login_open",
                "pixiv_login_check",
                "x_capture_open",
                "x_capture_close",
                "account_key_storage",
                "subscriptions_list",
                "saved_searches_list",
                "saved_search_add",
                "saved_search_remove",
                "subscription_preview",
                "subscription_create",
                "subscription_update",
                "subscription_delete",
                "subscription_check",
                "subscriptions_check_all",
                "general_info",
                "language_current",
                "general_save",
                "proxy_info",
                "proxy_save",
                "proxy_test",
                "storage_info",
                "storage_usage",
                "storage_change",
                "storage_cancel_pending",
                "storage_dismiss_error",
                "storage_prepare",
                "restart_app",
            ]))
            .plugin(
                "x",
                tauri_build::InlinedPlugin::new()
                    .commands(&["bridge_response"])
                    .default_permission(tauri_build::DefaultPermissionRule::Allow(vec![
                        "allow-bridge-response".into(),
                    ])),
            ),
    )
    .expect("failed to build Tauri ACL")
}
